version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      SERVER_PORT: 8000
      ACCESS_TOKEN_SECRET: 'access_token_secret'
      REFRESH_TOKEN_SECRET: 'refresh_token_secret'
      DB_CLIENT: 'pg'
      DB_NAME: 'node-tasks'
      DB_HOST: 'postgres'  # Use the service name as the hostname
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_PORT: '5432'
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node-tasks
